/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import java.awt.Color;

/**
 *
 * @author nguye
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    
    Color DefaultColor, ClickedColor;
    public Menu() {
        initComponents();
        DefaultColor = new Color(204,255,255);
        ClickedColor = new Color(204,204,204);
        
        TextSP.setBackground(DefaultColor);
     //   textNV.setBackground(DefaultColor);
        textHD.setBackground(DefaultColor);
        textKH.setBackground(DefaultColor);
        textKM.setBackground(DefaultColor);
        textDangXuat.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Menu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        sanPham = new javax.swing.JPanel();
        TextSP = new javax.swing.JLabel();
        nhanVien = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        hoaDon = new javax.swing.JPanel();
        textHD = new javax.swing.JLabel();
        khachHang = new javax.swing.JPanel();
        textKH = new javax.swing.JLabel();
        khuyenMai = new javax.swing.JPanel();
        textKM = new javax.swing.JLabel();
        thongKe = new javax.swing.JPanel();
        textDangXuat = new javax.swing.JLabel();
        dangXuat = new javax.swing.JPanel();
        textDangXuat1 = new javax.swing.JLabel();
        jDesktopPanel = new javax.swing.JDesktopPane();

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Open letter.png"))); // NOI18N
        jLabel2.setText("Sản phẩm");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(479, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        Menu.setBackground(new java.awt.Color(204, 204, 204));
        Menu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Menu.setForeground(new java.awt.Color(255, 255, 255));
        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/shopping-cart_1.png"))); // NOI18N
        Menu.setText("SNEAKER SHOP");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Delete.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 100));

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        sanPham.setBackground(new java.awt.Color(204, 255, 255));
        sanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sanPhamMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sanPhamMousePressed(evt);
            }
        });

        TextSP.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        TextSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/running-shoe.png"))); // NOI18N
        TextSP.setText("Sản phẩm");
        TextSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextSPMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextSPMousePressed(evt);
            }
        });

        javax.swing.GroupLayout sanPhamLayout = new javax.swing.GroupLayout(sanPham);
        sanPham.setLayout(sanPhamLayout);
        sanPhamLayout.setHorizontalGroup(
            sanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextSP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sanPhamLayout.setVerticalGroup(
            sanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextSP, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        nhanVien.setBackground(new java.awt.Color(204, 255, 255));
        nhanVien.setMaximumSize(new java.awt.Dimension(95, 24));
        nhanVien.setMinimumSize(new java.awt.Dimension(95, 24));
        nhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nhanVienMousePressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/User group.png"))); // NOI18N
        jButton1.setText("Nhân viên");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nhanVienLayout = new javax.swing.GroupLayout(nhanVien);
        nhanVien.setLayout(nhanVienLayout);
        nhanVienLayout.setHorizontalGroup(
            nhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhanVienLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        nhanVienLayout.setVerticalGroup(
            nhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hoaDon.setBackground(new java.awt.Color(204, 255, 255));
        hoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hoaDonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hoaDonMousePressed(evt);
            }
        });

        textHD.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        textHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Price list.png"))); // NOI18N
        textHD.setText("Hóa đơn");
        textHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textHDMousePressed(evt);
            }
        });

        javax.swing.GroupLayout hoaDonLayout = new javax.swing.GroupLayout(hoaDon);
        hoaDon.setLayout(hoaDonLayout);
        hoaDonLayout.setHorizontalGroup(
            hoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textHD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hoaDonLayout.setVerticalGroup(
            hoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textHD, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        khachHang.setBackground(new java.awt.Color(204, 255, 255));
        khachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khachHangMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                khachHangMousePressed(evt);
            }
        });

        textKH.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        textKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Users.png"))); // NOI18N
        textKH.setText("Khách hàng");
        textKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textKHMousePressed(evt);
            }
        });

        javax.swing.GroupLayout khachHangLayout = new javax.swing.GroupLayout(khachHang);
        khachHang.setLayout(khachHangLayout);
        khachHangLayout.setHorizontalGroup(
            khachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textKH)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        khachHangLayout.setVerticalGroup(
            khachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textKH, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        khuyenMai.setBackground(new java.awt.Color(204, 255, 255));
        khuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khuyenMaiMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                khuyenMaiMousePressed(evt);
            }
        });

        textKM.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        textKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/voucher.png"))); // NOI18N
        textKM.setText("Khuyến mãi");
        textKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textKMMousePressed(evt);
            }
        });

        javax.swing.GroupLayout khuyenMaiLayout = new javax.swing.GroupLayout(khuyenMai);
        khuyenMai.setLayout(khuyenMaiLayout);
        khuyenMaiLayout.setHorizontalGroup(
            khuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khuyenMaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textKM)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        khuyenMaiLayout.setVerticalGroup(
            khuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(khuyenMaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textKM, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        thongKe.setBackground(new java.awt.Color(204, 255, 255));
        thongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thongKeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                thongKeMousePressed(evt);
            }
        });

        textDangXuat.setBackground(new java.awt.Color(204, 255, 255));
        textDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        textDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Properties.png"))); // NOI18N
        textDangXuat.setText("Thống kê");
        textDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textDangXuatMousePressed(evt);
            }
        });

        javax.swing.GroupLayout thongKeLayout = new javax.swing.GroupLayout(thongKe);
        thongKe.setLayout(thongKeLayout);
        thongKeLayout.setHorizontalGroup(
            thongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textDangXuat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        thongKeLayout.setVerticalGroup(
            thongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        dangXuat.setBackground(new java.awt.Color(204, 255, 255));
        dangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dangXuatMousePressed(evt);
            }
        });

        textDangXuat1.setBackground(new java.awt.Color(204, 255, 255));
        textDangXuat1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        textDangXuat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Log out.png"))); // NOI18N
        textDangXuat1.setText("Đăng xuất");
        textDangXuat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textDangXuat1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout dangXuatLayout = new javax.swing.GroupLayout(dangXuat);
        dangXuat.setLayout(dangXuatLayout);
        dangXuatLayout.setHorizontalGroup(
            dangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dangXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textDangXuat1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dangXuatLayout.setVerticalGroup(
            dangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dangXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textDangXuat1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sanPham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(khachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(khuyenMai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(thongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(sanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(khachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(khuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(thongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 530));

        jDesktopPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPanelLayout = new javax.swing.GroupLayout(jDesktopPanel);
        jDesktopPanel.setLayout(jDesktopPanelLayout);
        jDesktopPanelLayout.setHorizontalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        jDesktopPanelLayout.setVerticalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 870, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextSPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSPMouseClicked

    private void TextSPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextSPMousePressed
  
    }//GEN-LAST:event_TextSPMousePressed

    private void textHDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textHDMousePressed
        
    }//GEN-LAST:event_textHDMousePressed

    private void textKHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textKHMousePressed
       
    }//GEN-LAST:event_textKHMousePressed

    private void textKMMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textKMMousePressed
        
    }//GEN-LAST:event_textKMMousePressed

    private void textDangXuatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textDangXuatMousePressed
        
    }//GEN-LAST:event_textDangXuatMousePressed

    private void sanPhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sanPhamMousePressed
        sanPham.setBackground(ClickedColor);
        nhanVien.setBackground(DefaultColor);
        hoaDon.setBackground(DefaultColor);
        khachHang.setBackground(DefaultColor);
        khuyenMai.setBackground(DefaultColor);
        thongKe.setBackground(DefaultColor);
        dangXuat.setBackground(DefaultColor);
        
        Menu.setText("Sản phẩm");
    }//GEN-LAST:event_sanPhamMousePressed

    private void nhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhanVienMousePressed
        sanPham.setBackground(DefaultColor);
        nhanVien.setBackground(ClickedColor);
        hoaDon.setBackground(DefaultColor);
        khachHang.setBackground(DefaultColor);
        khuyenMai.setBackground(DefaultColor);
        thongKe.setBackground(DefaultColor);
        dangXuat.setBackground(DefaultColor);
        
        Menu.setText("Nhân viên");
    }//GEN-LAST:event_nhanVienMousePressed

    private void hoaDonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoaDonMousePressed
        sanPham.setBackground(DefaultColor);
        nhanVien.setBackground(DefaultColor);
        hoaDon.setBackground(ClickedColor);
        khachHang.setBackground(DefaultColor);
        khuyenMai.setBackground(DefaultColor);
        thongKe.setBackground(DefaultColor);
        dangXuat.setBackground(DefaultColor);
        
        Menu.setText("Hóa đơn");
    }//GEN-LAST:event_hoaDonMousePressed

    private void khachHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khachHangMousePressed
        sanPham.setBackground(DefaultColor);
        nhanVien.setBackground(DefaultColor);
        hoaDon.setBackground(DefaultColor);
        khachHang.setBackground(ClickedColor);
        khuyenMai.setBackground(DefaultColor);
        thongKe.setBackground(DefaultColor);
        dangXuat.setBackground(DefaultColor);
        
        Menu.setText("Khách hàng");
    }//GEN-LAST:event_khachHangMousePressed

    private void khuyenMaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khuyenMaiMousePressed
        sanPham.setBackground(DefaultColor);
        nhanVien.setBackground(DefaultColor);
        hoaDon.setBackground(DefaultColor);
        khachHang.setBackground(DefaultColor);
        khuyenMai.setBackground(ClickedColor);
        thongKe.setBackground(DefaultColor);
        dangXuat.setBackground(DefaultColor);
        
        Menu.setText("Khuyến mại");
    }//GEN-LAST:event_khuyenMaiMousePressed

    private void thongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongKeMousePressed
        sanPham.setBackground(DefaultColor);
        nhanVien.setBackground(DefaultColor);
        hoaDon.setBackground(DefaultColor);
        khachHang.setBackground(DefaultColor);
        khuyenMai.setBackground(DefaultColor);
        thongKe.setBackground(ClickedColor);
        dangXuat.setBackground(DefaultColor);
        
        Menu.setText("Thống kê");
    }//GEN-LAST:event_thongKeMousePressed

    private void sanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sanPhamMouseClicked
        Menu_SanPham menu1 = new Menu_SanPham();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(menu1).setVisible(true);
    }//GEN-LAST:event_sanPhamMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void textDangXuat1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textDangXuat1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDangXuat1MousePressed

    private void dangXuatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dangXuatMousePressed
        sanPham.setBackground(DefaultColor);
        nhanVien.setBackground(DefaultColor);
        hoaDon.setBackground(DefaultColor);
        khachHang.setBackground(DefaultColor);
        khuyenMai.setBackground(DefaultColor);
        thongKe.setBackground(DefaultColor);
        dangXuat.setBackground(ClickedColor);
        
        Menu.setText("Đăng xuất");
    }//GEN-LAST:event_dangXuatMousePressed

    private void hoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoaDonMouseClicked
        Menu_HoaDon menu3 = new Menu_HoaDon();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(menu3).setVisible(true);
    }//GEN-LAST:event_hoaDonMouseClicked

    private void thongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongKeMouseClicked
        Menu_ThongKe menu6 = new Menu_ThongKe();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(menu6).setVisible(true);
    }//GEN-LAST:event_thongKeMouseClicked

    private void khuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khuyenMaiMouseClicked
        Menu_KhuyenMai menu7 = new Menu_KhuyenMai();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(menu7).setVisible(true);
    }//GEN-LAST:event_khuyenMaiMouseClicked

    private void khachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khachHangMouseClicked
        Menu_KhachHang menu4 = new Menu_KhachHang();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(menu4).setVisible(true);
    }//GEN-LAST:event_khachHangMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      View_NhanVien nhanVien = new View_NhanVien();
         nhanVien.setLocationRelativeTo(null);
         nhanVien.setVisible(true);
    // 4. (Tùy chọn) Đóng hoặc ẩn form hiện tại nếu không muốn dùng lại
    this.dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel TextSP;
    private javax.swing.JPanel dangXuat;
    private javax.swing.JPanel hoaDon;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel khachHang;
    private javax.swing.JPanel khuyenMai;
    private javax.swing.JPanel nhanVien;
    private javax.swing.JPanel sanPham;
    private javax.swing.JLabel textDangXuat;
    private javax.swing.JLabel textDangXuat1;
    private javax.swing.JLabel textHD;
    private javax.swing.JLabel textKH;
    private javax.swing.JLabel textKM;
    private javax.swing.JPanel thongKe;
    // End of variables declaration//GEN-END:variables
}
