/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;

import Repository.Repository_NhanVien;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.NhanVien;

/**
 *
 * @author nguye
 */
public class Menu_NhanVien extends javax.swing.JInternalFrame {
    private Repository.Repository_NhanVien rp = new Repository_NhanVien();
    private DefaultTableModel mol;
    private int i;
    /**
     * Creates new form Menu_NhanVien
     */
    public Menu_NhanVien() {
        initComponents();
        this.fillTable(rp.getAll());
        this.fillComboVT();
        this.fillComboLocVT();
        this.fillComboTT();
        this.fillComboLocTT();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui =(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }
    public void fillTable(List<NhanVien> list) {
        mol = (DefaultTableModel) tbl_QLNV.getModel();
        mol.setRowCount(0);
        for (NhanVien nv : list) {
            mol.addRow(new Object[]{
                nv.getIdNhanVien(),
                nv.getMaNhanVien(),
                nv.getHoTen(),
                nv.getGioiTinh(),
                nv.getSoDienThoai(),
                nv.getEmail(),
                nv.getMatKhau(),
                nv.getVaiTro() == 0 ? "Quản lý" : "Nhân viên",
                nv.getTrangThai() == 0 ? "Đang làm" : "Đã nghỉ"
            });
        }
    }

    public void fillComboVT() {
        DefaultComboBoxModel cmol = (DefaultComboBoxModel) cbo_vaiTro.getModel();
        cmol.removeAllElements();
        cmol.addElement("Quản lý");
        cmol.addElement("Nhân viên");
    }

    public void fillComboLocVT() {
        DefaultComboBoxModel cmol = (DefaultComboBoxModel) cboLocVT.getModel();
        cmol.removeAllElements();
        cmol.addElement("Tất cả");
        cmol.addElement("Quản lý");
        cmol.addElement("Nhân viên");
    }

    public void fillComboTT() {
        DefaultComboBoxModel cmol = (DefaultComboBoxModel) cbo_trangThai.getModel();
        cmol.removeAllElements();
        cmol.addElement("Đang làm");
        cmol.addElement("Đã nghỉ");
    }

    public void fillComboLocTT() {
        DefaultComboBoxModel cmol = (DefaultComboBoxModel) cboLocVT.getModel();
        cmol.removeAllElements();
        cmol.addElement("Tất cả");
        cmol.addElement("Đang làm");
        cmol.addElement("Đã nghỉ");
    }

    private void filterTable(String vaiTro, String keyword) {
        List<NhanVien> filteredList = new ArrayList<>();
        for (NhanVien nv : rp.getAll()) {
            boolean matchesVaiTro = vaiTro.equals("Tất cả")
                    || (nv.getVaiTro() == 0 && vaiTro.equals("Quản lý"))
                    || (nv.getVaiTro() == 1 && vaiTro.equals("Nhân viên"));
            boolean matchesKeyword = nv.getSoDienThoai().contains(keyword);  // Lọc theo số điện thoại

            if (matchesVaiTro && matchesKeyword) {
                filteredList.add(nv);
            }
        }
        fillTable(filteredList);
    }

    public void showData() {
        int row = tbl_QLNV.getSelectedRow();
        if (row >= 0) {
            txt_maNhanVien.setText(tbl_QLNV.getValueAt(row, 1).toString());
            txt_hoVaTen.setText(tbl_QLNV.getValueAt(row, 2).toString());
            String gioiTinh = tbl_QLNV.getValueAt(row, 3).toString();
            if (gioiTinh.equals("Nam")) {
                rdo_Nam.setSelected(true);
            } else {
                rdo_Nu.setSelected(true);
            }
            txt_SoDienThoai.setText(tbl_QLNV.getValueAt(row, 4).toString());
            txt_email.setText(tbl_QLNV.getValueAt(row, 5).toString());
            txt_matKhau.setText(tbl_QLNV.getValueAt(row, 6).toString());
            cbo_vaiTro.setSelectedItem(tbl_QLNV.getValueAt(row, 7).toString());
            cbo_trangThai.setSelectedItem(tbl_QLNV.getValueAt(row, 8).toString());

        }
    }

    private void clearForm() {
        txt_maNhanVien.setText("");
        txt_hoVaTen.setText("");
        txt_SoDienThoai.setText("");
        rdo_Nam.setSelected(false);
        rdo_Nu.setSelected(false);
        cbo_vaiTro.setSelectedIndex(-1);
        cbo_trangThai.setSelectedIndex(-1);
        txt_email.setText("");
        txt_matKhau.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_sua = new javax.swing.JButton();
        btnTCDS = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_lamMoi = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        rdo_Nu = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btn_xoa = new javax.swing.JButton();
        txt_maNhanVien = new javax.swing.JTextField();
        txt_SoDienThoai = new javax.swing.JTextField();
        cbo_vaiTro = new javax.swing.JComboBox<>();
        txt_hoVaTen = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_QLNV = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        rdo_Nam = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        cbo_trangThai = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        cboLocVT = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_matKhau = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(870, 530));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 90, -1));

        btnTCDS.setBackground(new java.awt.Color(51, 153, 255));
        btnTCDS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTCDS.setText("Tất cả danh sách");
        btnTCDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTCDSActionPerformed(evt);
            }
        });
        getContentPane().add(btnTCDS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Email:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Số điện thoại:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        btn_lamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Refresh.png"))); // NOI18N
        btn_lamMoi.setText("Làm mới");
        btn_lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamMoiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 200, -1));

        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        getContentPane().add(btn_them, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 200, 60));

        rdo_Nu.setText("Nữ");
        rdo_Nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_NuActionPerformed(evt);
            }
        });
        getContentPane().add(rdo_Nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Vai trò:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 160, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Mã nhân viên:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 100, -1));

        txt_maNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maNhanVienActionPerformed(evt);
            }
        });
        getContentPane().add(txt_maNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 150, -1));

        txt_SoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SoDienThoaiActionPerformed(evt);
            }
        });
        getContentPane().add(txt_SoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 150, -1));

        cbo_vaiTro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_vaiTro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_vaiTroActionPerformed(evt);
            }
        });
        getContentPane().add(cbo_vaiTro, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 160, -1));

        txt_hoVaTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hoVaTenActionPerformed(evt);
            }
        });
        getContentPane().add(txt_hoVaTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 150, -1));

        tbl_QLNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã nhân viên", "Họ và tên", "Giới tính", "Số điện thoại", "Email", "Mật khẩu", "Vai trò", "Trạng thái"
            }
        ));
        tbl_QLNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_QLNVMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_QLNV);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 840, 170));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Trạng thái:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, 19));

        rdo_Nam.setText("Nam");
        rdo_Nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_NamActionPerformed(evt);
            }
        });
        getContentPane().add(rdo_Nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Mật khẩu");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        cbo_trangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_trangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_trangThaiActionPerformed(evt);
            }
        });
        getContentPane().add(cbo_trangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 160, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null), "Tìm kiếm ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        cboLocVT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLocVT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLocVTActionPerformed(evt);
            }
        });

        jLabel6.setText("Vai Trò :");

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        btnTimKiem.setBackground(new java.awt.Color(204, 255, 255));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel7.setText("Tìm kiếm theo số điện thoại:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(cboLocVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimKiem)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboLocVT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem)
                    .addComponent(jLabel7))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 840, 80));

        txt_matKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matKhauActionPerformed(evt);
            }
        });
        getContentPane().add(txt_matKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 160, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Họ và tên:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Giới tính:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Thông tin nhân viên");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, 32));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed

        try {
            int row = tbl_QLNV.getSelectedRow();
            if (row < 0) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên để sửa");
                return;
            }

            int idNhanVien = Integer.parseInt(tbl_QLNV.getValueAt(row, 0).toString());

            String maNV = txt_maNhanVien.getText().trim();
            String hoTen = txt_hoVaTen.getText().trim();
            String sdt = txt_SoDienThoai.getText().trim();
            String email = txt_email.getText().trim();
            String matKhau = txt_matKhau.getText().trim();

            if (maNV.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không được để trống mã nhân viên");
                return;
            }

            if (hoTen.isEmpty() || !hoTen.matches("^[\\p{L}\\s]+$")) {
                JOptionPane.showMessageDialog(this, "Tên không hợp lệ. Chỉ được chứa chữ và khoảng trắng.");
                return;
            }

            if (sdt.isEmpty() || !sdt.matches("\\d{10}")) {
                JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ. Phải đúng 10 chữ số.");
                return;
            }

            if (email.isEmpty() || !email.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")) {
                JOptionPane.showMessageDialog(this, "Email không đúng định dạng");
                return;
            }

            if (matKhau.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không được để trống mật khẩu");
                return;
            }

            for (NhanVien nvOld : rp.getAll()) {
                if (nvOld.getIdNhanVien() != idNhanVien && nvOld.getMaNhanVien().equalsIgnoreCase(maNV)) {
                    JOptionPane.showMessageDialog(this, "Mã nhân viên đã tồn tại");
                    return;
                }
                if (nvOld.getIdNhanVien() != idNhanVien && nvOld.getSoDienThoai().equals(sdt)) {
                    JOptionPane.showMessageDialog(this, "Số điện thoại đã tồn tại");
                    return;
                }
                if (nvOld.getIdNhanVien() != idNhanVien && nvOld.getEmail().equalsIgnoreCase(email)) {
                    JOptionPane.showMessageDialog(this, "Email đã tồn tại");
                    return;
                }
            }

            String gioiTinh = rdo_Nam.isSelected() ? "Nam" : "Nữ";
            int idChucVu = 1;
            int vaiTro = cbo_vaiTro.getSelectedItem().toString().equals("Quản lý") ? 1 : 0;
            int trangThai = cbo_trangThai.getSelectedItem().toString().equals("Đang làm") ? 0 : 1;

            NhanVien nv = new NhanVien(
                idNhanVien,
                maNV,
                hoTen,
                gioiTinh,
                sdt,
                email,
                matKhau,
                idChucVu,
                vaiTro,
                trangThai
            );

            if (rp.update(nv) > 0) {
                fillTable(rp.getAll());
                JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thành công");
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thất bại");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi hệ thống, không thể cập nhật nhân viên");
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btnTCDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTCDSActionPerformed

    }//GEN-LAST:event_btnTCDSActionPerformed

    private void btn_lamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamMoiActionPerformed
        clearForm();
    }//GEN-LAST:event_btn_lamMoiActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        try {
            String maNV = txt_maNhanVien.getText().trim();
            String hoTen = txt_hoVaTen.getText().trim();
            String sdt = txt_SoDienThoai.getText().trim();
            String email = txt_email.getText().trim();
            String matKhau = txt_matKhau.getText().trim();

            if (maNV.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không được để trống mã nhân viên");
                return;
            }

            if (hoTen.isEmpty() || !hoTen.matches("^[\\p{L}\\s]+$")) {
                JOptionPane.showMessageDialog(this, "Tên không hợp lệ. Chỉ được chứa chữ và khoảng trắng.");
                return;
            }

            if (sdt.isEmpty() || !sdt.matches("\\d{10}")) {
                JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ. Phải đúng 10 chữ số.");
                return;
            }

            if (email.isEmpty() || !email.matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")) {
                JOptionPane.showMessageDialog(this, "Email không đúng định dạng");
                return;
            }

            if (matKhau.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không được để trống mật khẩu");
                return;
            }

            // Kiểm tra trùng dữ liệu
            for (NhanVien nvOld : rp.getAll()) {
                if (nvOld.getMaNhanVien().equalsIgnoreCase(maNV)) {
                    JOptionPane.showMessageDialog(this, "Mã nhân viên đã tồn tại");
                    return;
                }
                if (nvOld.getSoDienThoai().equals(sdt)) {
                    JOptionPane.showMessageDialog(this, "Số điện thoại đã tồn tại");
                    return;
                }
                if (nvOld.getEmail().equalsIgnoreCase(email)) {
                    JOptionPane.showMessageDialog(this, "Email đã tồn tại");
                    return;
                }
            }

            String gioiTinh = rdo_Nam.isSelected() ? "Nam" : "Nữ";
            int idChucVu = 1;

            int vaiTro = cbo_vaiTro.getSelectedItem().toString().equals("Quản lý") ? 1 : 0;
            int trangThai = cbo_trangThai.getSelectedItem().toString().equals("Đang làm") ? 0 : 1; // theo database bạn là 0=đang làm

            NhanVien nv = new NhanVien(
                0,
                maNV,
                hoTen,
                gioiTinh,
                sdt,
                email,
                matKhau,
                idChucVu,
                vaiTro,
                trangThai
            );

            if (rp.add(nv) > 0) {
                fillTable(rp.getAll());
                JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công");
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi thêm nhân viên");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi hệ thống, không thể thêm nhân viên");
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void rdo_NuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_NuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_NuActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        try {
            int row = tbl_QLNV.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần xóa");
                return;
            }

            String maNV = tbl_QLNV.getValueAt(row, 1).toString();
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn chuyển nhân viên này thành nghỉ việc?", "Xác nhận", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {

                if (rp.delete(maNV)) {
                    JOptionPane.showMessageDialog(this, "Xóa nhân viên thành công");
                    fillTable(rp.getAll());
                } else {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên để xóa");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi hệ thống, không thể xóa nhân viên");
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void txt_maNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maNhanVienActionPerformed

    private void txt_SoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SoDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SoDienThoaiActionPerformed

    private void cbo_vaiTroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_vaiTroActionPerformed

    }//GEN-LAST:event_cbo_vaiTroActionPerformed

    private void txt_hoVaTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hoVaTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hoVaTenActionPerformed

    private void tbl_QLNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_QLNVMouseClicked
        i = tbl_QLNV.getSelectedRow();
        showData();
    }//GEN-LAST:event_tbl_QLNVMouseClicked

    private void rdo_NamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_NamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_NamActionPerformed

    private void cbo_trangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_trangThaiActionPerformed

    }//GEN-LAST:event_cbo_trangThaiActionPerformed

    private void cboLocVTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLocVTActionPerformed

    }//GEN-LAST:event_cboLocVTActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String keyword = txtTimKiem.getText().trim();
        String vaiTro = cboLocVT.getSelectedItem() != null ? cboLocVT.getSelectedItem().toString() : "";
        filterTable(vaiTro, keyword);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void txt_matKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_matKhauActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTCDS;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btn_lamMoi;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cboLocVT;
    private javax.swing.JComboBox<String> cbo_trangThai;
    private javax.swing.JComboBox<String> cbo_vaiTro;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdo_Nam;
    private javax.swing.JRadioButton rdo_Nu;
    private javax.swing.JTable tbl_QLNV;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txt_SoDienThoai;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_hoVaTen;
    private javax.swing.JTextField txt_maNhanVien;
    private javax.swing.JTextField txt_matKhau;
    // End of variables declaration//GEN-END:variables
}
